package dev.ribica.oneblockplugin.oneblock;

import lombok.Getter;
import org.bukkit.Material;

/**
 * Represents a progression stage in the OneBlock game
 * Each stage has different blocks and mobs that can spawn
 */
public enum Stage {
    // TODO: ignore name and description, it was generated by ai anyway
    STAGE_1_PLAINS(1, Material.GRASS_BLOCK, "Plains", "The beginning of your journey"),
    STAGE_2_UNDERGROUND(2, Material.COBBLESTONE, "Underground", "Delve into the depths"),
    STAGE_3_OCEAN(3, Material.PRISMARINE, "Ocean", "Explore the seas"),
    STAGE_4_JUNGLE(4, Material.JUNGLE_WOOD, "Jungle", "Welcome to the wild"),
    STAGE_5_DESERT(5, Material.SAND, "Desert", "Feel the heat"),
    STAGE_6_ICE(6, Material.ICE, "Ice Plains", "Winter is coming"),
    STAGE_7_NETHER(7, Material.NETHERRACK, "Nether", "Enter the inferno"),
    STAGE_8_END(8, Material.END_STONE, "The End", "The final frontier");

    private final @Getter int level;
    private final @Getter Material icon;
//    private final @Getter String name;
//    private final @Getter String description;

    Stage(int level, Material icon, String name, String description) {
        this.level = level;
        this.icon = icon;
    }

    /**
     * Get a stage by its level number
     * @param level The level to look up
     * @return The corresponding Stage, or PLAINS if not found
     */
    public static Stage getByLevel(int level) {
        for (Stage stage : values()) {
            if (stage.level == level) {
                return stage;
            }
        }
        return STAGE_1_PLAINS; // Default to first stage
    }
}
